# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matVecProd <- function(m, v) {
    .Call('_PanelSelect_matVecProd', PACKAGE = 'PanelSelect', m, v)
}

matVecProdSum <- function(m, ext, v, group) {
    .Call('_PanelSelect_matVecProdSum', PACKAGE = 'PanelSelect', m, ext, v, group)
}

matVecProdSumExt <- function(m, ext, ext2, v, group) {
    .Call('_PanelSelect_matVecProdSumExt', PACKAGE = 'PanelSelect', m, ext, ext2, v, group)
}

groupProd <- function(v, group) {
    .Call('_PanelSelect_groupProd', PACKAGE = 'PanelSelect', v, group)
}

groupSum <- function(v, group) {
    .Call('_PanelSelect_groupSum', PACKAGE = 'PanelSelect', v, group)
}

groupSumMat <- function(m, group) {
    .Call('_PanelSelect_groupSumMat', PACKAGE = 'PanelSelect', m, group)
}

